### ISSUE TITLE
Getting error while when inviting user flow in GetUserTokenAsync

### ISSUE THREAD

**Issue by yadavvineet** [mrochon/b2c-mt-webapp#3]
Hi Marius, 
First of great library. Its one of the very few good integrations i have seen in past some time. 
I am facing an issue while trying to invoke the invite function. I am not sure where exactly is RCA for this, but may be if you can help out where to look. 
Please find the screenshot attached. when getting token, it gives an error: _Account username: missing form the token response._

![image](https://user-images.githubusercontent.com/7949851/96748097-ba10c880-13e6-11eb-9236-e23dddcd7bbc.png)

After this, it returns null in the following flow and it further downstream call fails.
![image](https://user-images.githubusercontent.com/7949851/96748830-b29def00-13e7-11eb-9584-68a532d8a22e.png)

**Comment by mrochon** [comment]
Thanks for your feedback. I suspect the error is caused by the browser using cookies from a previous session. If you restart your app on the server but use the same browser process as you used in an earlier session, the server will get the previous authentication cookies but will not be able to find the user's tokens in memory cache anymore. That will throw this error. Please restart the browser window or use incognito after shutting down the server. Let me know whether that fixes it.

**Comment by yadavvineet** [comment]
No, It didnt worked out :(
I did some more exploration. Please see the details if you can make out anything. 

Cache object  (deserialized) captured from here: https://github.com/mrochon/b2c-mt-webapp/blob/master/Extensions/TokenService.cs#L56
It seems username claim is not captured or fwded. 

- i am using Azure ad b2c account (abc@xyz.onmicrosoft.com) to login. 

- I have deployed in the policies manually after some changes, so I might have inadvertently did some changes. 

![image](https://user-images.githubusercontent.com/7949851/96899124-27d3f780-14ae-11eb-937c-a4512cfaa83b.png)

**Comment by mrochon** [comment]
Do not use a @xyz.onmicrosoft.com account. You need to use the signup functionality to create a regular B2C account, not a domain account. The only time you use the onmicrosoft.com account in B2C context is when you access the AAD portal itself.

**Comment by yadavvineet** [comment]
Thanks for quick response. I tried with personal account (personal@gmail.com). Even with that i am getting the same error. i guess PreferredUsername claim is not being set somehow. see the following screenshot from cache : 

![image](https://user-images.githubusercontent.com/7949851/96902407-1db3f800-14b2-11eb-9587-5105e50aa8bb.png)

**Comment by mrochon** [comment]
Ping me at sailingrock@live.com - let's set up a screen share/call. I am not sure user names matter to token cache operations.

**Comment by yadavvineet** [comment]
> Ping me at [sailingrock@live.com](mailto:sailingrock@live.com) - let's set up a screen share/call. I am not sure user names matter to token cache operations.

pinged you on skype, just revert back whenever u r  free, Not sure if something changed in base library 😮

**Comment by yadavvineet** [comment]
Thanks a lot for the help. For any body struggling, i was facing a problem that access token was null. This was due to the fact that the application for Rest functions was not created and scope was asking for it,  This is required for one of the scope: "**https://xyz.onmicrosoft.com/B2CRestAPIs/Members.ReadAll**"
Steps i did, create app for rest functions, named it B2CRestAPIs and exposed api Members.ReadAll
so that the   the scope becomes valid.

Thanks @mrochon for your support for OpenSource
